# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d828731f508a04380b043cc40ee841f5426128c63b855eec6d5ffcf8a1d439e4ba23e2fb3ef196c094ffa3db2c36a4a22eec444c8746f5530b224f75d689941

test:
  secret_key_base: 012e087810ea8dc5d4c5e75a69cd8fce028fb6e762ffe8cbb621383da26ace9d2e12c216d35157ab73e4d9de2dd23c59fb73182be4f5cfe0f8faecafb3b78443

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
